server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-stacktrace: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  security:
    oauth2:
      client:
        registration:
          anyone-dashboard:
            # https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html
            client-id: anyone-dashboard
#            client-secret: BoZjHZaFPkbPz6dac1Bj7VkOwuHRH9eT
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/anyone-dashboard"
            scope: openid,profile
        provider:
          anyone-dashboard:
            # https://lemur-15.cloud-iam.com/auth/realms/chocolate/.well-known/openid-configuration
            authorization-uri: https://lemur-15.cloud-iam.com/auth/realms/chocolate/protocol/openid-connect/auth
            token-uri: https://lemur-15.cloud-iam.com/auth/realms/chocolate/protocol/openid-connect/token
            user-info-uri: https://lemur-15.cloud-iam.com/auth/realms/chocolate/protocol/openid-connect/userinfo
            jwk-set-uri: https://lemur-15.cloud-iam.com/auth/realms/chocolate/protocol/openid-connect/certs
            user-name-attribute: preferred_username
